name: Build

on:
  push:

jobs:
  tests-linux:
    name: Run Tests (Linux)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Love 2D
      run:  |
        curl -L -o love https://github.com/love2d/love/releases/download/11.3/love-11.3-x86_64.AppImage
        chmod +x love
        echo "::add-path::${{ github.workspace }}"
    - name: Run Crystal Tests
      run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" love .
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test-output
        path: "*.png"
